Prevent memory leaks when resolving relations/links
storyblok/storyblok-js-client pull request #269
Opened 2022-08-26 13:23 UTC by Schinkentanz

Hey there,

the Storyblok JS client causes massive memory leaks and performance degradation when using the `resolve_relations` or `resolve_links` feature, because the client keeps references of each fetched story in an object ([relations](https://github.com/storyblok/storyblok-js-client/blob/46945964b54fbd4903015b3743d15c335710befe/source/index.js#L54) or [links](https://github.com/storyblok/storyblok-js-client/blob/46945964b54fbd4903015b3743d15c335710befe/source/index.js#L55)), without clearing them.

## Pull request type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

You can use the following test script along with the `package.json`, to check the current implementation and the changes from this pull request. Make sure to use the correct package `storyblok-js-client` or `storyblok-js-client-fix` for each test and make sure that the fetched pages have links and/or relations configured in SB. Run the script as follows and then connect to node using the chrome dev tools via `chrome://inspect` in order to record an _Allocation instrumentation timeline_ or just watch the `--trace-gc` outputs: 

```bash
node --inspect --trace-gc index.js
```

<details>
  <summary>Show test script & package.json</summary>

```json
{
  "name": "sb-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "storyblok-js-client": "4.5.6",
    "storyblok-js-client-fix": "https://github.com/Schinkentanz/storyblok-js-client#3059606",
  }
}

```

```js
// const Storyblok = require('storyblok-js-client');
const Storyblok = require('storyblok-js-client-fix');

const resolveRelations = '<redacted>';

const storyblok = new Storyblok({
  accessToken: '<redacted>'
});

(async () => {
  // Give dev 10s to connect to dev tools
  await new Promise(resolve => setTimeout(resolve, 10000));

  for (let index = 0; index < 150; index++) {
    const memoryUsageBefore = memory();

    await storyblok.getStories({
      resolve_links: 'story',
      starts_with: '<redacted>',
      filter_query: {
        component: { in: '<redacted>' }
      },
      resolve_relations: resolveRelations,
      page: index + 1,
      per_page: 100
    });

    const memoryUsageAfter = memory();

    // eslint-disable-next-line
    console.log(`request: ${index} | heap: ${memoryUsageBefore} -> ${memoryUsageAfter} MB`);
  }

  // Keep process & storyblok instance alive for further investigations
  await new Promise(resolve => setTimeout(() => {
    resolve(storyblok);
  }, 1000000));
})();

function memory() {
  return (process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2);
}
```
</details>

## What is the new behavior?
With the current version, the memory won't be freed (see blue columns that are indicating stuff that is kept in memory) and we end up with `~93 MB` of used memory (killed the script before reaching 150 reqs. because it would take forever)
![Pasted Graphic 2](https://user-images.githubusercontent.com/1647548/186907195-1fd30b35-59f4-42ce-a037-69e76835091c.png)

With the pull request changes, the memory will be freed once a request is completed which results in around `~6.5 MB` of data being kept in memory:
![image](https://user-images.githubusercontent.com/1647548/186911608-3033dd4d-46db-4e34-a592-3eb3a70feb25.png)

2022-09-09 21:33 UTC, thiagosaife requested changes
@Schinkentanz thanks for the awesome job. I request little changes about files that are not supposed to be inside the project. About your implementation, you changed the object's structure for `links` and `relations`. Yet you delete them at the. Why's this? Are they holding references that must purged at the end? Furthermore, these required parameter resolveId, could not be set once at the outer scope and got from there?

2022-09-09 21:33 UTC, thiagosaife commented on .editorconfig
> +root = true
Please, remove this file from your PR.

2022-09-09 21:33 UTC, thiagosaife commented on .gitignore
> +.idea
Since this folder doesn't belong to the project, please remove the reference from .gitignore and don't upload the folder with your PR.

2022-09-10 08:59 UTC, Schinkentanz commented
Hey @thiagosaife thanks for having a look. I added the requested changes to the `.editorconfig` & `.gitignore` files.

> About your implementation, you changed the object's structure for links and relations. Yet you delete them at the. Why's this? Are they holding references that must purged at the end? ...

The `resolveCount` counter keeps track of requests that are using the `resolve_relations` or `links` features. The `resolveId` created during the request ensures that the fetched relation/link stories can be deleted after the request is complete, otherwise this would result in a memory leak.

> Furthermore, these required parameter resolveId, could not be set once at the outer scope and got from there?

I'm pretty sure this could be improved by refactoring the resolving process in general so that it's not necessary to drag around the `resolveId`, but that's probably beyond the scope of this bugfix pull-req 😅

2022-09-29 10:24 UTC, mhcom commented
Hi @thiagosaife, any update on the review? This should make it into the JS client as soon as possible, as the current Storyblok client has massive performance issues, which makes it near impossible to request a large amount of data from the content delivery API.

2022-10-17 14:17 UTC, closed without merging