Feature/api v2
storyblok/storyblok-js-client pull request #74
Opened 2020-11-20 12:26 UTC by onefriendaday

* Adds support for api v2 and sets it as default endpoint

2020-11-20 17:45 UTC, ademarCardoso reviewed
Great job, I made some comments about the variables' delacrations, but the job is awesome 🚀

2020-11-20 17:45 UTC, ademarCardoso commented on source/index.js
> +    var enrich = (jtree) => {
Change `var enrich` to `const enrich`

2020-11-20 17:45 UTC, ademarCardoso commented on source/index.js
> +        for (var item = 0; item < jtree.length; item++) {
Change `var item` to `let item`

2020-11-20 17:45 UTC, ademarCardoso commented on source/index.js
> +        for (var treeItem in jtree) {
Change to `let`

2020-11-20 17:45 UTC, ademarCardoso commented on source/index.js
> +              var stories = []
Change to `const` or `let`

2020-11-20 17:45 UTC, ademarCardoso commented on source/index.js
> +      for (var chunkIndex = 0; chunkIndex < chunks.length; chunkIndex++) {
Change to `let`

2020-11-20 17:45 UTC, ademarCardoso commented on tests/resolveRelations.test.js
> +    for (var i = 0; i < 100; i++) {
Change to `let`

2020-11-23 17:28 UTC, emanuelgsouza requested changes
There are some errors in the TravisCI related to 404 in tests. Could you take a look? In the rest, that's a good job.

2020-11-23 17:28 UTC, emanuelgsouza commented on tests/redirect.test.js
> +const StoryblokClient = require('../source/index')
Could you change the import logic to use EsModules?

2020-11-23 17:28 UTC, emanuelgsouza commented on tests/resolveRelations.test.js
> +const StoryblokClient = require('../source/index')
Could you change the import logic to use EsModules?

2020-11-25 13:23 UTC, thiagosaife reviewed
Ran the tests here and everything is all right. Great job!

2020-11-27 17:07 UTC, emanuelgsouza approved these changes

2020-12-03 00:03 UTC, mAAdhaTTah commented on source/index.js
> +          if (params.version == 'draft' && cacheVersions[params.token] != response.data.cv) {
second half of this conditional will always be `false` cuz you're setting it to that value the line before.

2020-12-04 10:52 UTC, rokinsky commented on source/index.js
> -  newVersion() {
@onefriendaday it seems to me that you haven't updated the type definitions in `types/index.d.ts`

2020-12-07 19:22 UTC, rokinsky commented
General note: why are you resolving relationships here? As for me, such code isn't related to the client and the backend should do it instead.

2020-12-07 19:30 UTC, onefriendaday commented
> General note: why are you resolving relationships here? As for me, such code isn't related to the client and the backend should do it instead.

This version will use the new api endpoint v2/ where relationships are included in an additional array outside the content. This will avoid that duplicated content items are included in the content and a content item is only included once. The client then insert this relationships that come from the api into the content. This way the user can use the new api v2 without the need to update their implementations.

2020-12-07 20:03 UTC, rokinsky commented
> > General note: why are you resolving relationships here? As for me, such code isn't related to the client and the backend should do it instead.
> 
> This version will use the new api endpoint v2/ where relationships are included in an additional array outside the content. This will avoid that duplicated content items are included in the content and a content item is only included once. The client then insert this relationships that come from the api into the content. This way the user can use the new api v2 without the need to update their implementations.

Got it, just for backward compatibility. Thanks for the explanation @onefriendaday!

2021-04-23 19:26 UTC, merged

2021-04-23 19:28 UTC, emanuelgsouza commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/storyblok-js-client/v/4.0.0)
- [GitHub release](https://github.com/storyblok/storyblok-js-client/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: